// V2 re-export barrel
export type {
  MeridioProject,
  Layer,
  ProjectState,
  PlayType,
  TimingWindow,
  AlertThreshold,
  WindowType,
  ProjectEvent,
  EventType,
  EventSource,
  CompletionType,
  UrgencyLevel,
  UrgencyGroup,
  LayerDefinition,
  TransitionRule,
  TransitionRisk,
  TransitionValidation,
  LegacyProjectData,
  NFTWLTemplate,
  FastPlayTemplate,
  ProperProjectTemplate,
  TechStartupTemplate,
  TemplateData,
} from './types/project';

export {
  computeUrgencyLevel,
  computeIsStale,
  computeUrgencyGroup,
  STALE_THRESHOLDS_DAYS,
  DEFAULT_STATE_PER_LAYER,
  LAYER_DEFINITIONS,
  TRANSITION_RULES,
  validateTransition,
  getTransitionRule,
  createLayerTransitionEvent,
  appendEvent,
  loadProjectsFromStorage,
  saveProjectsToStorage,
  detectSchemaVersion,
  migrateV0ToV1,
  migrateAllProjects,
  STORAGE_KEYS,
} from './types/project';
